title: Aman Kumar
logo: /assets/img/headshot_circle.png
#description: text below image
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
show_downloads: false
theme: jekyll-theme-minimal

